### ISSUE TITLE
UnicodeDecodeErrors when using non ascii characters in dir path

### ISSUE THREAD

**Issue by sergiusens** [snapcrafters/magic-wormhole#5]
sergiusens@tupa:~/Vídeos$ wormhole recieve 
Enter receive wormhole code: 6-consensus-deckhand
Traceback (most recent call last):
  File "/snap/wormhole/23/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/snap/wormhole/23/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/snap/wormhole/23/lib/python2.7/site-packages/wormhole/cli/cmd_receive.py", line 174, in _go
    yield self._parse_offer(them_d[u"offer"], w)
  File "/snap/wormhole/23/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/snap/wormhole/23/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/snap/wormhole/23/lib/python2.7/site-packages/wormhole/cli/cmd_receive.py", line 253, in _parse_offer
    f = self._handle_file(them_d)
  File "/snap/wormhole/23/lib/python2.7/site-packages/wormhole/cli/cmd_receive.py", line 280, in _handle_file
    file_data["filename"])
  File "/snap/wormhole/23/lib/python2.7/site-packages/wormhole/cli/cmd_receive.py", line 322, in _decide_destname
    abs_destname = os.path.abspath( os.path.join(self.args.cwd, destname) )
  File "/snap/wormhole/23/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 18: ordinal not in range(128)
ERROR: 'ascii' codec can't decode byte 0xc3 in position 18: ordinal not in range(128)

**Comment by sergiusens** [comment]
this should be solved with #12 as well

```
$ wormhole send Задание/
Building zipfile..
Sending directory (10.4 MB compressed) named 'Задание'
Wormhole code is: 7-leprosy-mohawk
On the other computer, please run:

wormhole receive 7-leprosy-mohawk
```
